//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 28 15:23:52 CET 2015
//----------------------------------------------------

package java_cup;

/**
 * CUP generated interface containing symbol constants.
 */
public interface sym {
    /* terminals */
    int WITH = 11;
    int CODE_STRING = 35;
    int PARSER = 6;
    int SEMI = 13;
    int INIT = 9;
    int STAR = 15;
    int SCAN = 10;
    int BAR = 19;
    int LT = 29;
    int COMMA = 14;
    int NON = 8;
    int CLASS = 33;
    int CODE = 4;
    int DOT = 16;
    int ID = 34;
    int LEFT = 21;
    int EOF = 0;
    int SUPER = 31;
    int error = 1;
    int START = 12;
    int NONTERMINAL = 27;
    int ACTION = 5;
    int LBRACK = 25;
    int IMPORT = 3;
    int COLON = 17;
    int RBRACK = 26;
    int PACKAGE = 2;
    int NONASSOC = 23;
    int EXTENDS = 32;
    int PRECEDENCE = 20;
    int QUESTION = 30;
    int PERCENT_PREC = 24;
    int TERMINAL = 7;
    int RIGHT = 22;
    int GT = 28;
    int COLON_COLON_EQUALS = 18;

    /* non terminals */
    int NT$3 = 49;
    int empty = 28;
    int NT$2 = 48;
    int NT$1 = 47;
    int NT$0 = 46;
    int package_spec = 1;
    int class_name = 35;
    int precedence_list = 29;
    int wildcard = 45;
    int production_list = 11;
    int action_code_part = 3;
    int production = 21;
    int opt_label = 39;
    int nt_id = 36;
    int parser_code_part = 8;
    int type_id = 18;
    int spec = 0;
    int terminal_id = 40;
    int precedence_l = 32;
    int symbol = 17;
    int import_spec = 13;
    int start_spec = 10;
    int multipart_id = 12;
    int declares_non_term = 34;
    int NT$13 = 59;
    int term_name_list = 19;
    int NT$12 = 58;
    int NT$11 = 57;
    int NT$10 = 56;
    int import_list = 2;
    int init_code = 15;
    int typearguement = 44;
    int code_part = 5;
    int new_non_term_id = 25;
    int declares_term = 33;
    int preced = 30;
    int term_id = 41;
    int rhs = 27;
    int label_id = 38;
    int opt_semi = 6;
    int prod_part_list = 22;
    int robust_id = 42;
    int typearglist = 43;
    int new_term_id = 24;
    int prod_part = 23;
    int code_parts = 4;
    int scan_code = 16;
    int symbol_list = 9;
    int terminal_list = 31;
    int non_term_name_list = 20;
    int import_id = 14;
    int NT$9 = 55;
    int symbol_id = 37;
    int NT$8 = 54;
    int NT$7 = 53;
    int NT$6 = 52;
    int rhs_list = 26;
    int non_terminal = 7;
    int NT$5 = 51;
    int NT$4 = 50;
}
