//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package net.katagaitai.phpscan.ast;

/**
 * CUP generated interface containing symbol constants.
 */
public interface ParserConstants {
    /* terminals */
    int T_BOOLEAN_AND = 103;
    int T_INLINE_HTML = 11;
    int T_EMPTY = 49;
    int T_PROTECTED = 146;
    int T_CLOSE_RECT = 137;
    int T_TRAIT_C = 158;
    int T_IS_NOT_EQUAL = 108;
    int T_INCLUDE = 77;
    int T_OPEN_TAG_WITH_ECHO = 15;
    int T_QUATE = 152;
    int T_GLOBAL = 45;
    int T_PRINT = 86;
    int T_OR_EQUAL = 95;
    int T_LOGICAL_XOR = 84;
    int T_FUNCTION = 36;
    int T_STATIC = 142;
    int T_NEKUDA = 125;
    int T_THROW = 42;
    int T_CLASS = 51;
    int T_ABSTRACT = 143;
    int T_ENCAPSED_AND_WHITESPACE = 13;
    int T_MOD_EQUAL = 93;
    int T_BREAK = 33;
    int T_WHILE = 18;
    int T_DO = 17;
    int T_CONST = 37;
    int T_CONTINUE = 34;
    int T_FUNC_C = 61;
    int T_DIV = 121;
    int T_LOGICAL_OR = 83;
    int T_DIR = 73;
    int T_OPEN_PARENTHESE = 148;
    int T_REFERENCE = 106;
    int T_COMMA = 82;
    int T_FINALLY = 43;
    int T_ELSE = 141;
    int T_IS_EQUAL = 107;
    int T_LIST = 57;
    int T_NAMESPACE = 71;
    int T_NS_SEPARATOR = 74;
    int T_OR = 104;
    int T_IS_IDENTICAL = 109;
    int T_INC = 126;
    int T_ELSEIF = 140;
    int T_TRY = 40;
    int T_PRIVATE = 145;
    int T_UNSET_CAST = 134;
    int T_INCLUDE_ONCE = 78;
    int T_ENDIF = 139;
    int T_SR_EQUAL = 98;
    int EOF = 0;
    int T_CALLABLE = 157;
    int T_PUBLIC = 147;
    int T_OBJECT_OPERATOR = 55;
    int T_TILDA = 124;
    int T_PAAMAYIM_NEKUDOTAYIM = 70;
    int T_IS_SMALLER_OR_EQUAL = 111;
    int T_ELLIPSIS = 159;
    int T_XOR_EQUAL = 96;
    int T_ENDFOREACH = 23;
    int T_CONSTANT_ENCAPSED_STRING = 14;
    int T_BACKQUATE = 153;
    int T_AT = 135;
    int T_AS = 28;
    int T_CURLY_CLOSE = 69;
    int T_ENDDECLARE = 25;
    int T_CATCH = 41;
    int T_CASE = 31;
    int T_VARIABLE = 9;
    int T_INSTEADOF = 155;
    int T_NEW = 138;
    int T_MINUS_EQUAL = 89;
    int T_PLUS = 117;
    int T_SL_EQUAL = 97;
    int T_ENDWHILE = 19;
    int T_ENDFOR = 21;
    int T_TRAIT = 156;
    int T_CLONE = 27;
    int T_BOOLEAN_OR = 102;
    int T_UNSET = 47;
    int T_INTERFACE = 52;
    int T_SWITCH = 29;
    int T_IS_GREATER_OR_EQUAL = 112;
    int T_OPEN_RECT = 136;
    int T_CURLY_OPEN_WITH_DOLAR = 67;
    int T_FINAL = 144;
    int T_REQUIRE = 80;
    int T_FILE = 63;
    int T_DEC = 127;
    int T_CLOSE_PARENTHESE = 149;
    int T_CLASS_C = 59;
    int T_EVAL = 79;
    int T_POW = 120;
    int T_RGREATER = 113;
    int T_IS_NOT_IDENTICAL = 110;
    int T_NOT = 123;
    int T_REQUIRE_ONCE = 81;
    int T_POW_EQUAL = 99;
    int T_NS_C = 72;
    int T_DOLLAR_OPEN_CURLY_BRACES = 66;
    int T_VAR = 46;
    int T_START_HEREDOC = 64;
    int T_ENDSWITCH = 30;
    int T_OBJECT_CAST = 132;
    int T_ECHO = 16;
    int T_LINE = 62;
    int T_FOR = 20;
    int T_IMPLEMENTS = 54;
    int T_ARRAY_CAST = 131;
    int T_CHARACTER = 12;
    int T_DOLLAR = 151;
    int T_TIMES = 119;
    int T_DOUBLE_CAST = 129;
    int T_BOOL_CAST = 133;
    int T_PRECENT = 122;
    int T_LNUMBER = 4;
    int T_CURLY_OPEN = 68;
    int T_DEFINE = 76;
    int T_QUESTION_MARK = 100;
    int T_USE = 44;
    int T_KOVA = 105;
    int T_IF = 3;
    int T_MUL_EQUAL = 90;
    int T_ARRAY = 58;
    int T_LGREATER = 114;
    int T_SEMICOLON = 101;
    int T_NEKUDOTAIM = 150;
    int T_VAR_COMMENT = 75;
    int T_CONCAT_EQUAL = 92;
    int T_YIELD = 39;
    int T_SINGLE_QUATE = 154;
    int T_AND_EQUAL = 94;
    int T_DNUMBER = 5;
    int T_MINUS = 118;
    int T_FOREACH = 22;
    int T_EXIT = 2;
    int T_DECLARE = 24;
    int T_STRING_VARNAME = 8;
    int T_EXTENDS = 53;
    int T_METHOD_C = 60;
    int T_INT_CAST = 128;
    int T_ISSET = 48;
    int T_LOGICAL_AND = 85;
    int error = 1;
    int T_RETURN = 38;
    int T_DEFAULT = 32;
    int T_SR = 116;
    int T_BNUMBER = 6;
    int T_EQUAL = 87;
    int T_SL = 115;
    int T_END_HEREDOC = 65;
    int T_DOUBLE_ARROW = 56;
    int T_STRING_CAST = 130;
    int T_STRING = 7;
    int T_PLUS_EQUAL = 88;
    int T_INSTANCEOF = 26;
    int T_DIV_EQUAL = 91;
    int T_NUM_STRING = 10;
    int T_HALT_COMPILER = 50;
    int T_GOTO = 35;
    String[] terminalNames = new String[]{
            "EOF",
            "error",
            "T_EXIT",
            "T_IF",
            "T_LNUMBER",
            "T_DNUMBER",
            "T_BNUMBER",
            "T_STRING",
            "T_STRING_VARNAME",
            "T_VARIABLE",
            "T_NUM_STRING",
            "T_INLINE_HTML",
            "T_CHARACTER",
            "T_ENCAPSED_AND_WHITESPACE",
            "T_CONSTANT_ENCAPSED_STRING",
            "T_OPEN_TAG_WITH_ECHO",
            "T_ECHO",
            "T_DO",
            "T_WHILE",
            "T_ENDWHILE",
            "T_FOR",
            "T_ENDFOR",
            "T_FOREACH",
            "T_ENDFOREACH",
            "T_DECLARE",
            "T_ENDDECLARE",
            "T_INSTANCEOF",
            "T_CLONE",
            "T_AS",
            "T_SWITCH",
            "T_ENDSWITCH",
            "T_CASE",
            "T_DEFAULT",
            "T_BREAK",
            "T_CONTINUE",
            "T_GOTO",
            "T_FUNCTION",
            "T_CONST",
            "T_RETURN",
            "T_YIELD",
            "T_TRY",
            "T_CATCH",
            "T_THROW",
            "T_FINALLY",
            "T_USE",
            "T_GLOBAL",
            "T_VAR",
            "T_UNSET",
            "T_ISSET",
            "T_EMPTY",
            "T_HALT_COMPILER",
            "T_CLASS",
            "T_INTERFACE",
            "T_EXTENDS",
            "T_IMPLEMENTS",
            "T_OBJECT_OPERATOR",
            "T_DOUBLE_ARROW",
            "T_LIST",
            "T_ARRAY",
            "T_CLASS_C",
            "T_METHOD_C",
            "T_FUNC_C",
            "T_LINE",
            "T_FILE",
            "T_START_HEREDOC",
            "T_END_HEREDOC",
            "T_DOLLAR_OPEN_CURLY_BRACES",
            "T_CURLY_OPEN_WITH_DOLAR",
            "T_CURLY_OPEN",
            "T_CURLY_CLOSE",
            "T_PAAMAYIM_NEKUDOTAYIM",
            "T_NAMESPACE",
            "T_NS_C",
            "T_DIR",
            "T_NS_SEPARATOR",
            "T_VAR_COMMENT",
            "T_DEFINE",
            "T_INCLUDE",
            "T_INCLUDE_ONCE",
            "T_EVAL",
            "T_REQUIRE",
            "T_REQUIRE_ONCE",
            "T_COMMA",
            "T_LOGICAL_OR",
            "T_LOGICAL_XOR",
            "T_LOGICAL_AND",
            "T_PRINT",
            "T_EQUAL",
            "T_PLUS_EQUAL",
            "T_MINUS_EQUAL",
            "T_MUL_EQUAL",
            "T_DIV_EQUAL",
            "T_CONCAT_EQUAL",
            "T_MOD_EQUAL",
            "T_AND_EQUAL",
            "T_OR_EQUAL",
            "T_XOR_EQUAL",
            "T_SL_EQUAL",
            "T_SR_EQUAL",
            "T_POW_EQUAL",
            "T_QUESTION_MARK",
            "T_SEMICOLON",
            "T_BOOLEAN_OR",
            "T_BOOLEAN_AND",
            "T_OR",
            "T_KOVA",
            "T_REFERENCE",
            "T_IS_EQUAL",
            "T_IS_NOT_EQUAL",
            "T_IS_IDENTICAL",
            "T_IS_NOT_IDENTICAL",
            "T_IS_SMALLER_OR_EQUAL",
            "T_IS_GREATER_OR_EQUAL",
            "T_RGREATER",
            "T_LGREATER",
            "T_SL",
            "T_SR",
            "T_PLUS",
            "T_MINUS",
            "T_TIMES",
            "T_POW",
            "T_DIV",
            "T_PRECENT",
            "T_NOT",
            "T_TILDA",
            "T_NEKUDA",
            "T_INC",
            "T_DEC",
            "T_INT_CAST",
            "T_DOUBLE_CAST",
            "T_STRING_CAST",
            "T_ARRAY_CAST",
            "T_OBJECT_CAST",
            "T_BOOL_CAST",
            "T_UNSET_CAST",
            "T_AT",
            "T_OPEN_RECT",
            "T_CLOSE_RECT",
            "T_NEW",
            "T_ENDIF",
            "T_ELSEIF",
            "T_ELSE",
            "T_STATIC",
            "T_ABSTRACT",
            "T_FINAL",
            "T_PRIVATE",
            "T_PROTECTED",
            "T_PUBLIC",
            "T_OPEN_PARENTHESE",
            "T_CLOSE_PARENTHESE",
            "T_NEKUDOTAIM",
            "T_DOLLAR",
            "T_QUATE",
            "T_BACKQUATE",
            "T_SINGLE_QUATE",
            "T_INSTEADOF",
            "T_TRAIT",
            "T_CALLABLE",
            "T_TRAIT_C",
            "T_ELLIPSIS"
    };
}
