//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package net.katagaitai.phpscan.ast;

/** CUP generated interface containing symbol constants. */
public interface ParserConstants {
	/* terminals */
	public static final int T_BOOLEAN_AND = 103;
	public static final int T_INLINE_HTML = 11;
	public static final int T_EMPTY = 49;
	public static final int T_PROTECTED = 146;
	public static final int T_CLOSE_RECT = 137;
	public static final int T_TRAIT_C = 158;
	public static final int T_IS_NOT_EQUAL = 108;
	public static final int T_INCLUDE = 77;
	public static final int T_OPEN_TAG_WITH_ECHO = 15;
	public static final int T_QUATE = 152;
	public static final int T_GLOBAL = 45;
	public static final int T_PRINT = 86;
	public static final int T_OR_EQUAL = 95;
	public static final int T_LOGICAL_XOR = 84;
	public static final int T_FUNCTION = 36;
	public static final int T_STATIC = 142;
	public static final int T_NEKUDA = 125;
	public static final int T_THROW = 42;
	public static final int T_CLASS = 51;
	public static final int T_ABSTRACT = 143;
	public static final int T_ENCAPSED_AND_WHITESPACE = 13;
	public static final int T_MOD_EQUAL = 93;
	public static final int T_BREAK = 33;
	public static final int T_WHILE = 18;
	public static final int T_DO = 17;
	public static final int T_CONST = 37;
	public static final int T_CONTINUE = 34;
	public static final int T_FUNC_C = 61;
	public static final int T_DIV = 121;
	public static final int T_LOGICAL_OR = 83;
	public static final int T_DIR = 73;
	public static final int T_OPEN_PARENTHESE = 148;
	public static final int T_REFERENCE = 106;
	public static final int T_COMMA = 82;
	public static final int T_FINALLY = 43;
	public static final int T_ELSE = 141;
	public static final int T_IS_EQUAL = 107;
	public static final int T_LIST = 57;
	public static final int T_NAMESPACE = 71;
	public static final int T_NS_SEPARATOR = 74;
	public static final int T_OR = 104;
	public static final int T_IS_IDENTICAL = 109;
	public static final int T_INC = 126;
	public static final int T_ELSEIF = 140;
	public static final int T_TRY = 40;
	public static final int T_PRIVATE = 145;
	public static final int T_UNSET_CAST = 134;
	public static final int T_INCLUDE_ONCE = 78;
	public static final int T_ENDIF = 139;
	public static final int T_SR_EQUAL = 98;
	public static final int EOF = 0;
	public static final int T_CALLABLE = 157;
	public static final int T_PUBLIC = 147;
	public static final int T_OBJECT_OPERATOR = 55;
	public static final int T_TILDA = 124;
	public static final int T_PAAMAYIM_NEKUDOTAYIM = 70;
	public static final int T_IS_SMALLER_OR_EQUAL = 111;
	public static final int T_ELLIPSIS = 159;
	public static final int T_XOR_EQUAL = 96;
	public static final int T_ENDFOREACH = 23;
	public static final int T_CONSTANT_ENCAPSED_STRING = 14;
	public static final int T_BACKQUATE = 153;
	public static final int T_AT = 135;
	public static final int T_AS = 28;
	public static final int T_CURLY_CLOSE = 69;
	public static final int T_ENDDECLARE = 25;
	public static final int T_CATCH = 41;
	public static final int T_CASE = 31;
	public static final int T_VARIABLE = 9;
	public static final int T_INSTEADOF = 155;
	public static final int T_NEW = 138;
	public static final int T_MINUS_EQUAL = 89;
	public static final int T_PLUS = 117;
	public static final int T_SL_EQUAL = 97;
	public static final int T_ENDWHILE = 19;
	public static final int T_ENDFOR = 21;
	public static final int T_TRAIT = 156;
	public static final int T_CLONE = 27;
	public static final int T_BOOLEAN_OR = 102;
	public static final int T_UNSET = 47;
	public static final int T_INTERFACE = 52;
	public static final int T_SWITCH = 29;
	public static final int T_IS_GREATER_OR_EQUAL = 112;
	public static final int T_OPEN_RECT = 136;
	public static final int T_CURLY_OPEN_WITH_DOLAR = 67;
	public static final int T_FINAL = 144;
	public static final int T_REQUIRE = 80;
	public static final int T_FILE = 63;
	public static final int T_DEC = 127;
	public static final int T_CLOSE_PARENTHESE = 149;
	public static final int T_CLASS_C = 59;
	public static final int T_EVAL = 79;
	public static final int T_POW = 120;
	public static final int T_RGREATER = 113;
	public static final int T_IS_NOT_IDENTICAL = 110;
	public static final int T_NOT = 123;
	public static final int T_REQUIRE_ONCE = 81;
	public static final int T_POW_EQUAL = 99;
	public static final int T_NS_C = 72;
	public static final int T_DOLLAR_OPEN_CURLY_BRACES = 66;
	public static final int T_VAR = 46;
	public static final int T_START_HEREDOC = 64;
	public static final int T_ENDSWITCH = 30;
	public static final int T_OBJECT_CAST = 132;
	public static final int T_ECHO = 16;
	public static final int T_LINE = 62;
	public static final int T_FOR = 20;
	public static final int T_IMPLEMENTS = 54;
	public static final int T_ARRAY_CAST = 131;
	public static final int T_CHARACTER = 12;
	public static final int T_DOLLAR = 151;
	public static final int T_TIMES = 119;
	public static final int T_DOUBLE_CAST = 129;
	public static final int T_BOOL_CAST = 133;
	public static final int T_PRECENT = 122;
	public static final int T_LNUMBER = 4;
	public static final int T_CURLY_OPEN = 68;
	public static final int T_DEFINE = 76;
	public static final int T_QUESTION_MARK = 100;
	public static final int T_USE = 44;
	public static final int T_KOVA = 105;
	public static final int T_IF = 3;
	public static final int T_MUL_EQUAL = 90;
	public static final int T_ARRAY = 58;
	public static final int T_LGREATER = 114;
	public static final int T_SEMICOLON = 101;
	public static final int T_NEKUDOTAIM = 150;
	public static final int T_VAR_COMMENT = 75;
	public static final int T_CONCAT_EQUAL = 92;
	public static final int T_YIELD = 39;
	public static final int T_SINGLE_QUATE = 154;
	public static final int T_AND_EQUAL = 94;
	public static final int T_DNUMBER = 5;
	public static final int T_MINUS = 118;
	public static final int T_FOREACH = 22;
	public static final int T_EXIT = 2;
	public static final int T_DECLARE = 24;
	public static final int T_STRING_VARNAME = 8;
	public static final int T_EXTENDS = 53;
	public static final int T_METHOD_C = 60;
	public static final int T_INT_CAST = 128;
	public static final int T_ISSET = 48;
	public static final int T_LOGICAL_AND = 85;
	public static final int error = 1;
	public static final int T_RETURN = 38;
	public static final int T_DEFAULT = 32;
	public static final int T_SR = 116;
	public static final int T_BNUMBER = 6;
	public static final int T_EQUAL = 87;
	public static final int T_SL = 115;
	public static final int T_END_HEREDOC = 65;
	public static final int T_DOUBLE_ARROW = 56;
	public static final int T_STRING_CAST = 130;
	public static final int T_STRING = 7;
	public static final int T_PLUS_EQUAL = 88;
	public static final int T_INSTANCEOF = 26;
	public static final int T_DIV_EQUAL = 91;
	public static final int T_NUM_STRING = 10;
	public static final int T_HALT_COMPILER = 50;
	public static final int T_GOTO = 35;
	public static final String[] terminalNames = new String[] {
			"EOF",
			"error",
			"T_EXIT",
			"T_IF",
			"T_LNUMBER",
			"T_DNUMBER",
			"T_BNUMBER",
			"T_STRING",
			"T_STRING_VARNAME",
			"T_VARIABLE",
			"T_NUM_STRING",
			"T_INLINE_HTML",
			"T_CHARACTER",
			"T_ENCAPSED_AND_WHITESPACE",
			"T_CONSTANT_ENCAPSED_STRING",
			"T_OPEN_TAG_WITH_ECHO",
			"T_ECHO",
			"T_DO",
			"T_WHILE",
			"T_ENDWHILE",
			"T_FOR",
			"T_ENDFOR",
			"T_FOREACH",
			"T_ENDFOREACH",
			"T_DECLARE",
			"T_ENDDECLARE",
			"T_INSTANCEOF",
			"T_CLONE",
			"T_AS",
			"T_SWITCH",
			"T_ENDSWITCH",
			"T_CASE",
			"T_DEFAULT",
			"T_BREAK",
			"T_CONTINUE",
			"T_GOTO",
			"T_FUNCTION",
			"T_CONST",
			"T_RETURN",
			"T_YIELD",
			"T_TRY",
			"T_CATCH",
			"T_THROW",
			"T_FINALLY",
			"T_USE",
			"T_GLOBAL",
			"T_VAR",
			"T_UNSET",
			"T_ISSET",
			"T_EMPTY",
			"T_HALT_COMPILER",
			"T_CLASS",
			"T_INTERFACE",
			"T_EXTENDS",
			"T_IMPLEMENTS",
			"T_OBJECT_OPERATOR",
			"T_DOUBLE_ARROW",
			"T_LIST",
			"T_ARRAY",
			"T_CLASS_C",
			"T_METHOD_C",
			"T_FUNC_C",
			"T_LINE",
			"T_FILE",
			"T_START_HEREDOC",
			"T_END_HEREDOC",
			"T_DOLLAR_OPEN_CURLY_BRACES",
			"T_CURLY_OPEN_WITH_DOLAR",
			"T_CURLY_OPEN",
			"T_CURLY_CLOSE",
			"T_PAAMAYIM_NEKUDOTAYIM",
			"T_NAMESPACE",
			"T_NS_C",
			"T_DIR",
			"T_NS_SEPARATOR",
			"T_VAR_COMMENT",
			"T_DEFINE",
			"T_INCLUDE",
			"T_INCLUDE_ONCE",
			"T_EVAL",
			"T_REQUIRE",
			"T_REQUIRE_ONCE",
			"T_COMMA",
			"T_LOGICAL_OR",
			"T_LOGICAL_XOR",
			"T_LOGICAL_AND",
			"T_PRINT",
			"T_EQUAL",
			"T_PLUS_EQUAL",
			"T_MINUS_EQUAL",
			"T_MUL_EQUAL",
			"T_DIV_EQUAL",
			"T_CONCAT_EQUAL",
			"T_MOD_EQUAL",
			"T_AND_EQUAL",
			"T_OR_EQUAL",
			"T_XOR_EQUAL",
			"T_SL_EQUAL",
			"T_SR_EQUAL",
			"T_POW_EQUAL",
			"T_QUESTION_MARK",
			"T_SEMICOLON",
			"T_BOOLEAN_OR",
			"T_BOOLEAN_AND",
			"T_OR",
			"T_KOVA",
			"T_REFERENCE",
			"T_IS_EQUAL",
			"T_IS_NOT_EQUAL",
			"T_IS_IDENTICAL",
			"T_IS_NOT_IDENTICAL",
			"T_IS_SMALLER_OR_EQUAL",
			"T_IS_GREATER_OR_EQUAL",
			"T_RGREATER",
			"T_LGREATER",
			"T_SL",
			"T_SR",
			"T_PLUS",
			"T_MINUS",
			"T_TIMES",
			"T_POW",
			"T_DIV",
			"T_PRECENT",
			"T_NOT",
			"T_TILDA",
			"T_NEKUDA",
			"T_INC",
			"T_DEC",
			"T_INT_CAST",
			"T_DOUBLE_CAST",
			"T_STRING_CAST",
			"T_ARRAY_CAST",
			"T_OBJECT_CAST",
			"T_BOOL_CAST",
			"T_UNSET_CAST",
			"T_AT",
			"T_OPEN_RECT",
			"T_CLOSE_RECT",
			"T_NEW",
			"T_ENDIF",
			"T_ELSEIF",
			"T_ELSE",
			"T_STATIC",
			"T_ABSTRACT",
			"T_FINAL",
			"T_PRIVATE",
			"T_PROTECTED",
			"T_PUBLIC",
			"T_OPEN_PARENTHESE",
			"T_CLOSE_PARENTHESE",
			"T_NEKUDOTAIM",
			"T_DOLLAR",
			"T_QUATE",
			"T_BACKQUATE",
			"T_SINGLE_QUATE",
			"T_INSTEADOF",
			"T_TRAIT",
			"T_CALLABLE",
			"T_TRAIT_C",
			"T_ELLIPSIS"
	};
}
